{% set name = "rockverse" %}
{% set version = "1.1.1" %}
{% set python_min = "3.11" %}

package:
  name: {{ name|lower }}
  version: {{ version }}

source:
  url: https://pypi.org/packages/source/{{ name[0] }}/{{ name }}/rockverse-{{ version }}.tar.gz
  sha256: ba5c14e4505612320a68e6d41bbb209ca30a49c4dab933be456d166f28c2e6aa

build:
  noarch: python
  script: {{ PYTHON }} -m pip install . -vv --no-deps --no-build-isolation
  number: 0

requirements:
  host:
    - python {{ python_min }}
    - setuptools >=61.0
    - setuptools-scm
    - pip
  run:
    - python >={{ python_min }},<3.13
    - docutils >=0.17
    - ipympl
    - ipython
    - ipyparallel
    - ipywidgets
    - jupyter
    - jupyterlab
    - jupyter_contrib_nbextensions
    - matplotlib-base <3.10
    - mpi4py
    - myst-parser
    - nbsphinx
    - numba
    - numpy
    - pandas
    - pandoc
    - pip
    - pydata-sphinx-theme
    - scipy <=1.13.1
    - sphinx <8.2
    - sphinx-copybutton
    - sphinx-design
    - sphinx-gallery
    - tqdm
    - zarr >=3,<4

test:
  imports:
    - rockverse
  commands:
    - pip check
  requires:
    - python {{ python_min }}
    - pip

about:
  home: https://pypi.org/project/rockverse/
  dev_url: https://github.com/rodolfovictor/rockverse
  summary: Python tools for Computational Petrophysics
  license: MIT
  license_file: LICENSE.md

extra:
  recipe-maintainers:
    - rodolfovictor
