{% set name = "rockverse" %}
{% set version = "0.3.8" %}
{% set python_min = "3.11" %}

package:
  name: {{ name|lower }}
  version: {{ version }}

source:
  url: https://pypi.org/packages/source/{{ name[0] }}/{{ name }}/rockverse-{{ version }}.tar.gz
  sha256: 57337c8e38b2cfec997db4898716fb2157e9bf95a751cf7496515ec9d2664192

build:
  noarch: python
  script: {{ PYTHON }} -m pip install . -vv --no-deps --no-build-isolation
  number: 0

requirements:
  host:
    - python {{ python_min }}
    - setuptools >=61.0
    - setuptools-scm
    - pip
  run:
    - python >={{ python_min }},<3.13
    - ipympl
    - ipython
    - ipyparallel
    - ipywidgets
    - jupyter
    - jupyterlab
    - matplotlib-base <3.10
    - mpi4py
    - nbsphinx
    - numba
    - numpy
    - pandas
    - pip
    - pydata-sphinx-theme
    - scipy <=1.13.1
    - sphinx
    - sphinx-copybutton
    - sphinx-design
    - sphinx-gallery
    - tqdm
    - zarr <3

test:
  imports:
    - rockverse
  commands:
    - pip check
  requires:
    - python {{ python_min }}
    - pip

about:
  home: https://pypi.org/project/rockverse/
  dev_url: https://github.com/rodolfovictor/rockverse
  summary: Python tools for Computational Petrophysics
  license: MIT
  license_file: LICENSE

extra:
  recipe-maintainers:
    - rodolfovictor
